# Lot of time Model alone can not solve the Problems
# We need to give it some tools to help it solve the problems
# for example : Web search tool to get latest information from the web
# Calculator tool to do mathematical calculations
# Calendar tool to manage your schedule

# In Order to make use Custom Function calling we need to define the tools Schema
# This is done using JSON Schema
# Then we need to embed the tool schema in the prompt and define the function calling behaviour
# This is done by setting the function_call parameter to "auto" or "none" or
# We can also use the inbuilt tools provided by OpenAI

# Lesson1 Custom Tools and Function Calling
# First Define The Tool Schema (JSON Schema as suggested by OpenAI)
# https://platform.openai.com/docs/guides/function-calling (Link for explanation of JSON Schema)
from openai import OpenAI
import json
import os
from dotenv import load_dotenv


load_dotenv()

# Use environment variable for API key (secure approach)
# Create a .env file with: OPENAI_API_KEY=your_actual_api_key_here

client = OpenAI()  # Will automatically use OPENAI_API_KEY from environment



# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_shipment_status",
        "description": "Get the current status and location of a shipment by container number.",
        "parameters": {
            "type": "object",
            "properties": {
                "container_number": {
                    "type": "string",
                    "description": "The container tracking number (e.g., MAEU1234567)",
                },
            },
            "required": ["container_number"],
        },
    },
]

def get_shipment_status(container_number):
    return f"{container_number}: Your container is currently at Mumbai Port, scheduled to depart on 15th October."

# Create a running input list we will add to over time
input_list = [
    {"role": "user", "content": "Where is my shipment? Container number is MAEU1234567."}
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model="gpt-5-nano",
    tools=tools,
    input=input_list,
    instructions="Use Tools if you find it necessary."

)

#print("=== RAW RESPONSE ===")
#print(response)

# Save function call outputs for subsequent requests
input_list += response.output

print("=== INPUT SO FAR ===")
print(input_list)


for item in response.output:
    if item.type == "function_call":
        if item.name == "get_shipment_status":
            # 3. Execute the function logic for get_shipment_status
            status = get_shipment_status(json.loads(item.arguments))

            # 4. Provide function call results to the model
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                  "status": status
                })
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model="gpt-5",
    instructions="Respond only with shipment status information generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)
